# Generated by Django 3.2.6 on 2021-08-18 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField(verbose_name='쪽지')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='댓글')),
                ('pub_date', models.DateTimeField()),
                ('messageId', models.ForeignKey(db_column='MessageId', on_delete=django.db.models.deletion.CASCADE, to='message.message')),
                ('replyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.reply')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
